services:
  nestjs-rpgdb:
    image: postgres:latest
    container_name: nestjs-rpg-db
    ports:
      - "5435:5435"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "psqladminpass"
      POSTGRES_DB: "nestjs_rpgdb"
      PGPORT: 5435
    volumes:
      - postgres_data:/var/lib/postgresql/data

  nestjs-rpg-api:
    image: nestjs-rpg
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nestjs-rpg-api
    environment:
      - NODE_ENV=dev
      - PORT=3001
      - HOST=nestjs-rpg-db
    ports:
      - '3001:3001'
    depends_on:
      - nestjs-rpgdb
    volumes:
      - ./src:/app/src

volumes:
  postgres_data: