services:
  nestjs-rpgdb:
    image: postgres:16
    container_name: nestjs-rpgdb
    ports:
      - "5435:5435"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "psqladminpass"
      POSTGRES_DB: "nestjs_rpgdb"
      PGPORT: 5435
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data: